import { type NextPage } from "next";
import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "@/utils/api";
import DropHead from "@/components/battleDrops/DropHead";
import RecentlyAdded from "@/components/homePage/RecentSongs";
import RecentCreators from "@/components/homePage/RecentCreators";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NiftyTunes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DropHead />
      <div className="mt-20 flex flex-col space-y-14">
        <RecentlyAdded />
        <RecentCreators />
      </div>
    </>
  );
};

export default Home;
