import type { NextPage } from "next";
import DropHead from "@/components/soloDrops/DropHead";

const SoloDrops: NextPage = () => {
  return (
    <>
      {/* <Head>
        <title>NiftyTunes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <DropHead />
      {/* <div className="mt-20 flex flex-col space-y-14">
        <RecentlyAdded />
        <RecentCreators />
      </div> */}
    </>
  );
};

export default SoloDrops;
